jokes={"joke":[
{"id":134, "setup":"How do you organize a space party?", "punchline":"You planet."},
{"id":313, "setup":"What did one plate say to the other plate?", "punchline":"Dinner is on me!"},
{"id":139, "setup":"Want to hear a joke about construction?", "punchline":"Nah, I'm still working on it."},
{"id":195, "setup":"How much does a hipster weigh?", "punchline":"An instagram."},
{"id":270, "setup":"What do you call an elephant that doesn't matter?", "punchline":"An irrelephant."},
{"id":296, "setup":"What is the hardest part about sky diving?", "punchline":"The ground."},
{"id":308, "setup":"What is this movie about?", "punchline":"It is about 2 hours long."},
{"id":91, "setup":"What do you call an alligator in a vest?", "punchline":"An in-vest-igator!"},
{"id":43, "setup":"Where do young cows eat lunch?", "punchline":"In the calf-ateria."},
{"id":121, "setup":"If you boil a clown...", "punchline":"Do you get a laughing stock?"},
{"id":44, "setup":"What kind of music do planets listen to?", "punchline":"Nep-tunes."},
{"id":129, "setup":"What was the pumpkin's favorite sport?", "punchline":"Squash."},
{"id":232, "setup":"What's blue and not very heavy?", "punchline":"Light blue."},
{"id":182, "setup":"What happens to a frog's car when it breaks down?", "punchline":"It gets toad away"},
{"id":56, "setup":"What do you call a bear with no teeth?", "punchline":"A gummy bear!"},
{"id":128, "setup":"What kind of award did the dentist receive?", "punchline":"A little plaque."},
{"id":32, "setup":"What do you do when you see a space man?", "punchline":"Park your car, man."},
{"id":271, "setup":"What do you call a belt made out of watches?", "punchline":"A waist of time."},
{"id":143, "setup":"Why did the man put his money in the freezer?", "punchline":"He wanted cold hard cash!"},
{"id":17, "setup":"Why are graveyards so noisy?", "punchline":"Because of all the coffin."},
{"id":321, "setup":"Which side of the chicken has more feathers?", "punchline":"The outside."},
{"id":199, "setup":"What's E.T. short for?", "punchline":"He's only got little legs."},
{"id":60, "setup":"What kind of pants do ghosts wear?", "punchline":"Boo jeans."},
{"id":146, "setup":"what do you call a dog that can do magic tricks?", "punchline":"a labracadabrador"},
{"id":96, "setup":"How do locomotives know where they're going?", "punchline":"Lots of training"},
{"id":250, "setup":"Why can't your nose be 12 inches long?", "punchline":"Because then it'd be a foot!"},
{"id":184, "setup":"How do you make holy water?", "punchline":"You boil the hell out of it."},
{"id":54, "setup":"What does a female snake use for support?", "punchline":"A co-Bra!"},
{"id":74, "setup":"I was gonna tell you a joke about UDP...", "punchline":"...but you might not get it."},
{"id":309, "setup":"What do you call someone with no nose?", "punchline":"Nobody knows."},
{"id":221, "setup":"How do you get a baby alien to sleep?", "punchline":"You rocket."},
{"id":12, "setup":"What did one nut say as he chased another nut?", "punchline":"I'm a cashew!"},
{"id":249, "setup":"What do ghosts call their true love?", "punchline":"Their ghoul-friend"},
{"id":312, "setup":"How many lips does a flower have?", "punchline":"Tulips"},
{"id":233, "setup":"What do you call a fake noodle?", "punchline":"An impasta."},
{"id":123, "setup":"Why did the butcher work extra hours at the shop?", "punchline":"To make ends meat."},
{"id":284, "setup":"Why do crabs never give to charity?", "punchline":"Because they're shellfish."},
{"id":246, "setup":"What's the best thing about elevator jokes?", "punchline":"They work on so many levels."},
{"id":260, "setup":"What do you call a fat psychic?", "punchline":"A four-chin teller."},
{"id":144, "setup":"What's the best time to go to the dentist?", "punchline":"Tooth hurty."},
{"id":112, "setup":"What do you call a pile of cats?", "punchline":"A Meowtain."},
{"id":133, "setup":"What do you call a bee that lives in America?", "punchline":"A USB."},
{"id":141, "setup":"What did the grape do when he got stepped on?", "punchline":"He let out a little wine."},
{"id":290, "setup":"Why did Dracula lie in the wrong coffin?", "punchline":"He made a grave mistake."},
{"id":244, "setup":"How does the moon cut his hair?", "punchline":"Eclipse it."},
{"id":208, "setup":"What do you call a group of disorganized cats?", "punchline":"A cat-tastrophe."},
{"id":159, "setup":"How do you fix a damaged jack-o-lantern?", "punchline":"You use a pumpkin patch."},
{"id":16, "setup":"What do you call a laughing motorcycle?", "punchline":"A Yamahahahaha."},
{"id":117, "setup":"Is the pool safe for diving?", "punchline":"It deep ends."},
{"id":64, "setup":"I'm reading a book about anti-gravity...", "punchline":"It's impossible to put down"},
{"id":93, "setup":"What's black and white and read all over?", "punchline":"The newspaper."},
{"id":65, "setup":"What did the ocean say to the beach?", "punchline":"Thanks for all the sediment."},
{"id":263, "setup":"Can February march?", "punchline":"No, but April may."},
{"id":86, "setup":"What does a clock do when it's hungry?", "punchline":"It goes back four seconds!"},
{"id":188, "setup":"Why can't a bicycle stand on its own?", "punchline":"It's two-tired."},
{"id":176, "setup":"What musical instrument is found in the bathroom?", "punchline":"A tuba toothpaste."},
{"id":49, "setup":"What do you call a sheep with no legs?", "punchline":"A cloud."},
{"id":180, "setup":"Where does Fonzie like to go for lunch?", "punchline":"Chick-Fil-Eyyyyyyyy."},
{"id":285, "setup":"Why did the cookie cry?", "punchline":"It was feeling crumby."},
{"id":80, "setup":"Why did the octopus beat the shark in a fight?", "punchline":"Because it was well armed."},
{"id":257, "setup":"Did you hear about the Mexican train killer?", "punchline":"He had loco motives"},
{"id":71, "setup":"Which song would an exception sing?", "punchline":"Can't catch me - Avicii"},
{"id":110, "setup":"What do you call sad coffee?", "punchline":"Despresso."},
{"id":194, "setup":"Why did the melons plan a big wedding?", "punchline":"Because they cantaloupe!"},
{"id":36, "setup":"Why do bears have hairy coats?", "punchline":"Fur protection."},
{"id":9, "setup":"Did you hear about the hungry clock?", "punchline":"It went back four seconds."},
{"id":186, "setup":"Hey, dad, did you get a haircut?", "punchline":"No, I got them all cut."},
{"id":207, "setup":"Did you hear about the two silk worms in a race?", "punchline":"It ended in a tie."},
{"id":235, "setup":"What do you call a dictionary on drugs?", "punchline":"High definition."},
{"id":183, "setup":"How are false teeth like stars?", "punchline":"They come out at night!"},
{"id":22, "setup":"How many bones are in the human hand?", "punchline":"A handful of them."},
{"id":29, "setup":"What do you call a fly without wings?", "punchline":"A walk."},
{"id":15, "setup":"What is the leading cause of dry skin?", "punchline":"Towels"},
{"id":236, "setup":"What is red and smells like blue paint?", "punchline":"Red paint!"},
{"id":6, "setup":"I couldn't get a reservation at the library...", "punchline":"They were fully booked."},
{"id":39, "setup":"How does a train eat?", "punchline":"It goes chew, chew"},
{"id":181, "setup":"What do you call a duck that gets all A's?", "punchline":"A wise quacker."},
{"id":248, "setup":"What's red and bad for your teeth?", "punchline":"A Brick."},
{"id":10, "setup":"What do you get when you cross a bee and a sheep?", "punchline":"A bah-humbug."},
{"id":120, "setup":"What do you give to a lemon in need?", "punchline":"Lemonaid."},
{"id":50, "setup":"Where was the Declaration of Independence signed?", "punchline":"At the bottom!"},
{"id":125, "setup":"Why did the programmer quit his job?", "punchline":"Because he didn't get arrays."},
{"id":85, "setup":"What's 50 Cent's name in Zimbabwe?", "punchline":"200 Dollars."},
{"id":140, "setup":"How was the snow globe feeling after the storm?", "punchline":"A little shaken."},
{"id":67, "setup":"What did one snowman say to the other snow man?", "punchline":"Do you smell carrot?"},
{"id":201, "setup":"What did the late tomato say to the early tomato?", "punchline":"I'll ketch up"},
{"id":307, "setup":"Bad at golf?", "punchline":"Join the club."},
{"id":172, "setup":"Why do mathematicians hate the U.S.?", "punchline":"Because it's indivisible."},
{"id":27, "setup":"What did the duck say when he bought lipstick?", "punchline":"Put it on my bill"},
{"id":38, "setup":"Can I watch the TV?", "punchline":"Yes, but don't turn it on."},
{"id":283, "setup":"Why did the mushroom get invited to the party?", "punchline":"Because he was a fungi."},
{"id":111, "setup":"What do birds give out on Halloween?", "punchline":"Tweets."},
{"id":152, "setup":"What's brown and sticky?", "punchline":"A stick."},
{"id":102, "setup":"What do you call corn that joins the army?", "punchline":"Kernel."},
{"id":77, "setup":"Did you hear about the submarine industry?", "punchline":"It really took a dive..."},
{"id":226, "setup":"Why did the belt go to prison?", "punchline":"He held up a pair of pants!"},
{"id":28, "setup":"Why did the house go to the doctor?", "punchline":"It was having window panes."},
{"id":240, "setup":"Want to hear my pizza joke?", "punchline":"Never mind, it's too cheesy."},
{"id":124, "setup":"Why does Superman get invited to dinners?", "punchline":"Because he is a Supperhero."},
{"id":135, "setup":"What is a tornado's favorite game to play?", "punchline":"Twister!"},
{"id":87, "setup":"Never take advice from electrons.", "punchline":"They are always negative."},
{"id":268, "setup":"How does a dyslexic poet write?", "punchline":"Inverse."},
{"id":138, "setup":"Did you watch the new comic book movie?", "punchline":"It was very graphic!"},
{"id":166, "setup":"When is a door not a door?", "punchline":"When it's ajar."},
{"id":227, "setup":"What did the mountain climber name his son?", "punchline":"Cliff."},
{"id":305, "setup":"Where do bees go to the bathroom?", "punchline":"The BP station."},
{"id":258, "setup":"Dad, can you put my shoes on?", "punchline":"I don't think they'll fit me."},
{"id":273, "setup":"What's orange and sounds like a parrot?", "punchline":"A Carrot."},
{"id":161, "setup":"Why is peter pan always flying?", "punchline":"Because he neverlands"},
{"id":107, "setup":"What kind of dinosaur loves to sleep?", "punchline":"A stega-snore-us."},
{"id":211, "setup":"Where do sheep go to get their hair cut?", "punchline":"The baa-baa shop."},
{"id":193, "setup":"Did you hear the joke about the wandering nun?", "punchline":"She was a roman catholic."},
{"id":154, "setup":"An IPv6 packet is walking out of the house.", "punchline":"He goes nowhere."},
{"id":21, "setup":"Why couldn't the lifeguard save the hippie?", "punchline":"He was too far out, man."},
{"id":274, "setup":"What does a pirate pay for his corn?", "punchline":"A buccaneer!"},
{"id":286, "setup":"What cheese can never be yours?", "punchline":"Nacho cheese."},
{"id":189, "setup":"Did you know crocodiles could grow up to 15 feet?", "punchline":"But most just have 4."},
{"id":218, "setup":"Why couldn't the kid see the pirate movie?", "punchline":"Because it was rated arrr!"},
{"id":84, "setup":"What did the pirate say on his 80th birthday?", "punchline":"Aye Matey!"},
{"id":174, "setup":"What kind of magic do cows believe in?", "punchline":"MOODOO."},
{"id":255, "setup":"What do prisoners use to call each other?", "punchline":"Cell phones."},
{"id":220, "setup":"Why do ducks make great detectives?", "punchline":"They always quack the case."},
{"id":151, "setup":"What kind of tree fits in your hand?", "punchline":"A palm tree!"},
{"id":90, "setup":"Where do programmers like to hangout?", "punchline":"The Foo Bar."},
{"id":214, "setup":"How can you tell a vampire has a cold?", "punchline":"They start coffin."},
{"id":31, "setup":"Why didn't the number 4 get into the nightclub?", "punchline":"Because he is 2 square."},
{"id":298, "setup":"Why are fish so smart?", "punchline":"Because they live in schools!"},
{"id":302, "setup":"What do you call a girl between two posts?", "punchline":"Annette."},
{"id":57, "setup":"What's Forest Gump's Facebook password?", "punchline":"1forest1"},
{"id":231, "setup":"Why did the kid cross the playground?", "punchline":"To get to the other slide."},
{"id":153, "setup":"I had a dream that I was a muffler last night.", "punchline":"I woke up exhausted!"},
{"id":203, "setup":"Why did the barber win the race?", "punchline":"He took a short cut."},
{"id":25, "setup":"What did the ocean say to the shore?", "punchline":"Nothing, it just waved."},
{"id":99, "setup":"What do you call a cow with no legs?", "punchline":"Ground beef."},
{"id":35, "setup":"Why didn't the orange win the race?", "punchline":"It ran out of juice."},
{"id":8, "setup":"What do I look like?", "punchline":"A JOKE MACHINE!?"},
{"id":94, "setup":"What has ears but cannot hear?", "punchline":"A field of corn."},
{"id":204, "setup":"Where do rabbits go after they get married?", "punchline":"On a bunny-moon."},
{"id":209, "setup":"What do you call cheese by itself?", "punchline":"Provolone."},
{"id":45, "setup":"A termite walks into a bar and says...", "punchline":"'Where is the bar tended?'"},
{"id":145, "setup":"Want to hear a joke about a piece of paper?", "punchline":"Never mind...it's tearable"},
{"id":92, "setup":"What did the fish say when it hit the wall?", "punchline":"Dam."},
{"id":118, "setup":"What is the least spoken language in the world?", "punchline":"Sign Language"},
{"id":234, "setup":"Why did the tree go to the dentist?", "punchline":"It needed a root canal."},
{"id":69, "setup":"['hip', 'hip']", "punchline":"(hip hip array)"},
{"id":327, "setup":"What's brown and sounds like a bell?", "punchline":"Dung!"},
{"id":19, "setup":"What did the dog say to the two trees?", "punchline":"Bark bark."},
{"id":97, "setup":"How does a penguin build it's house?", "punchline":"Igloos it together."},
{"id":42, "setup":"Have you heard of the band 1023MB?", "punchline":"They haven't got a gig yet."},
{"id":147, "setup":"What biscuit does a short person like?", "punchline":"Shortbread."},
{"id":200, "setup":"What did the left eye say to the right eye?", "punchline":"Between us, something smells!"},
{"id":238, "setup":"Who is the coolest Doctor in the hospital?", "punchline":"The hip Doctor!"},
{"id":119, "setup":"What did the beaver say to the tree?", "punchline":"It's been nice gnawing you."},
{"id":101, "setup":"What kind of shoes does a thief wear?", "punchline":"Sneakers"},
{"id":79, "setup":"How do you organize an outer space party?", "punchline":"You planet"},
{"id":288, "setup":"Why did the coffee file a police report?", "punchline":"It got mugged."},
{"id":316, "setup":"What does an angry pepper do?", "punchline":"It gets jalapeno face."},
{"id":149, "setup":"What animal is always at a game of cricket?", "punchline":"A bat."},
{"id":78, "setup":"What creature is smarter than a talking parrot?", "punchline":"A spelling bee."},
{"id":136, "setup":"What did Michael Jackson name his denim store?", "punchline":"Billy Jeans!"},
{"id":26, "setup":"How does a scientist freshen their breath?", "punchline":"With experi-mints!"},
{"id":224, "setup":"Why did the girl smear peanut butter on the road?", "punchline":"To go with the traffic jam."},
{"id":299, "setup":"What time did the man go to the dentist?", "punchline":"Tooth hurt-y."},
{"id":7, "setup":"Where do hamburgers go to dance?", "punchline":"The meat-ball."},
{"id":212, "setup":"Why can't bicycles stand on their own?", "punchline":"They are two tired"},
{"id":55, "setup":"What do you call a cow on a trampoline?", "punchline":"A milk shake!"},
{"id":156, "setup":"What do you call an eagle who can play the piano?", "punchline":"Talonted!"},
{"id":247, "setup":"What do you call two barracuda fish?", "punchline":"A Pairacuda!"},
{"id":126, "setup":"What kind of bagel can fly?", "punchline":"A plain bagel."},
{"id":254, "setup":"Did you hear about the runner who was criticized?", "punchline":"He just took it in stride"},
{"id":245, "setup":"How do you find Will Smith in the snow?", "punchline":"Look for fresh prints."},
{"id":191, "setup":"Where did you learn to make ice cream?", "punchline":"Sunday school."},
]};